---
- name: Install apache2
  hosts: all
  remote_user: admin
  become: true
  become_method: sudo

  tasks: 
    - name: Install package apache2
      apt:
       name: apache2
       state: present
      when: ansible_os_family == "Ubuntu"
