---
- name: Install docker
  hosts: all
  remote_user: admin
  become: true
  become_method: sudo
  
  tasks:
  - name: Install docker
    pip: 
     name: docker-py
    when: ansible_hostname == "serverb"
