---
- name: "Install users"
  hosts: all 
  remote_user: admin
  become: true
  become_method: sudo
  vars:
    users:
      - sai
      - uman
      - tony
  
  tasks:
  - name: update the users
    user: 
      name: "{{ item }}"
      state: present
    with_items:  "{{ users }}"
